# Generated by Django 2.2.4 on 2019-08-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_oauth_application_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='start',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PackageDate',
        ),
    ]
