# Generated by Django 2.2.4 on 2019-08-28 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190828_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 22, 13, 40, 545215)),
        ),
    ]
