# Generated by Django 2.2.4 on 2019-08-29 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190829_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
