# Generated by Django 2.2.4 on 2019-09-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190829_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('waiting', 'waiting'), ('booked', 'booked'), ('cancelled', 'cancelled')], default='cart', max_length=30),
        ),
    ]
