# Generated by Django 2.2.4 on 2019-09-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Package')),
            ],
        ),
    ]
