# Generated by Django 2.2.4 on 2019-09-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190923_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
